Rails.application.config.assets.precompile += %w( backend.css public.css )
Rails.application.config.assets.precompile += %w( dashboard/* public/* )
Rails.application.config.assets.precompile += %w( user_dashboard.css )
Rails.application.config.assets.precompile += %w( user_dashboard.js )
Rails.application.config.assets.precompile += %w( public.js )
Rails.application.config.assets.precompile += %w( 3.1.1/* )
Rails.application.config.assets.precompile += %w( bootstrap-datepicker.js )